services:
  mongolocal:
    image: mongo:6.0
    container_name: mongolocal
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  api:
    build: ./backend
    container_name: products-api
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongolocal:27017/productsdb
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongolocal
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: